name: smart_home_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  syncfusion_flutter_gauges: ^27.1.48
  shared_preferences: ^2.0.5
  uuid: ^4.5.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  sqflite: ^2.4.0
  sqflite_common_ffi_web: ^0.4.5+3
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.26
  async: ^2.11.0
  path: ^1.9.0
  provider: ^6.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
