// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCETRAgjAGnBrvydsfY7nk4wmOtkaQjykg',
    appId: '1:66583068865:web:4ed23d4dcb985ec9d05440',
    messagingSenderId: '66583068865',
    projectId: 'smart-home-control-98900',
    authDomain: 'smart-home-control-98900.firebaseapp.com',
    storageBucket: 'smart-home-control-98900.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVLzLOz3XokRrIevcxps-A9W408Hxfg4U',
    appId: '1:66583068865:android:6031bcfed8c95e29d05440',
    messagingSenderId: '66583068865',
    projectId: 'smart-home-control-98900',
    storageBucket: 'smart-home-control-98900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVsGo6SekZRHhaAyfrbnQv7FfNoPlQ52U',
    appId: '1:66583068865:ios:25f97e60a9d69523d05440',
    messagingSenderId: '66583068865',
    projectId: 'smart-home-control-98900',
    storageBucket: 'smart-home-control-98900.appspot.com',
    iosBundleId: 'com.example.smartHomeControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVsGo6SekZRHhaAyfrbnQv7FfNoPlQ52U',
    appId: '1:66583068865:ios:25f97e60a9d69523d05440',
    messagingSenderId: '66583068865',
    projectId: 'smart-home-control-98900',
    storageBucket: 'smart-home-control-98900.appspot.com',
    iosBundleId: 'com.example.smartHomeControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCETRAgjAGnBrvydsfY7nk4wmOtkaQjykg',
    appId: '1:66583068865:web:1965ed0258cd86f6d05440',
    messagingSenderId: '66583068865',
    projectId: 'smart-home-control-98900',
    authDomain: 'smart-home-control-98900.firebaseapp.com',
    storageBucket: 'smart-home-control-98900.appspot.com',
  );

}